### ISSUE TITLE
Task 'run' not found in root project 'san_google_login'.

### ISSUE THREAD

**Issue by IhsanFajari14018** [gsuitedevs/java-samples#11]
(Please fill out these details before submitting an issue)

### Sample Name
(i.e. Gmail Quickstart)

### Expected Behavior
It should have run like this web said: 
https://developers.google.com/people/quickstart/java

### Actual Behavior
Turn out giving error like this:

* What went wrong:
Task 'run' nt found in root project 'san_google_login'.

FAILURE: build failed with an exception.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

### Specifications
  - Java version: 9.0.4
  - OS: Windows 7 Profesional, SP 1
  - Processor: Intel(R) Core(TM) i5-4200 CPU @1.60GHz 2.30GHz
  - RAM: 8Gb
  - System Type: 64-bit Operating System
  - System Model: X450LCP
  - System Manufacturer: ASUSTek COMPUTER INC.
  - DirectX 11

**Comment by erickoledadevrel** [comment]
Glad you found a solution. Can you post what it was, in others run into this issue in the future?

**Comment by IhsanFajari14018** [comment]
Sorrry I haven't installed the Gradle in my environment. After installing, the next time I run it the error doesn't appear anymore.
