### ISSUE TITLE
Issue while trying to use Google MailAPI client using Gradle

### ISSUE THREAD

**Issue by varanrajesh** [gsuitedevs/java-samples#15]
BUILD SUCCESSFUL in 2s
2 actionable tasks: 2 executed
rajesh-2755:Orgcreation rajesh-2755$ mkdir -p src/main/java src/main/resources
rajesh-2755:Orgcreation rajesh-2755$ gradle -q run
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
Error: Could not find or load main class GmailQuickstart

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by sqrrrl** [comment]
Was this just running the quickstart? Or were you trying to do something in your own project?

**Comment by grant** [comment]
It looks like this is running the Gmail Quickstart.

**Comment by grant** [comment]
@sqrrrl Can you triage this or unassign yourself?
This issue is probably from running the sample in the wrong directory like https://github.com/gsuitedevs/java-samples/issues/28.

**Comment by erickoledadevrel** [comment]
This is a different error than #28. Please follow #57 instead.

**Comment by varanrajesh** [comment]
running the quickstart
Thanks & Regards,
Rajeshwaran Angamuthu
900 345 8596
