### ISSUE TITLE
Google Drive Redirect URLs

### ISSUE THREAD

**Issue by shyamzzp** [gsuitedevs/java-samples#16]
(Please fill out these details before submitting an issue)

### Google Drive
(i.e. Gmail Quickstart)

### Expected Behavior
should be a single redirect url and there is no plcae to change inthe code for the single url
### Actual Behavior
Generating random urls so its difficult to add every redirect url to the console.developer.google.com

### Specifications
  - Java version (`java -version`)
  - OS (Mac/Linux/Windows)

**Comment by sqrrrl** [comment]
Can you give an example?

If you're referring to the port changing for the localhost URL, you don't need to register each one. The port is ignored on localhost URLs because it's expected that they're ephemeral.
