### ISSUE TITLE
CRM com agenda google como sincronizar as atividades locais com o google calendar

### ISSUE THREAD

**Issue by alexjosesilva** [gsuitedevs/java-samples#18]
(Please fill out these details before submitting an issue)

### Sample Name
(i.e. Gmail Quickstart)

### Specifications
  - Java version (`java -version`)
  - OS (Mac/Linux/Windows)

**Comment by asrivas** [comment]
Please see the Java sample here: https://developers.google.com/calendar/v3/sync
Let us know if you have any follow up questions

**Comment by grant** [comment]
The translation to English states:
CRM with google calendar how to sync local activities with google calendar

Given the lack of response, and other issues with respect to the Gmail Quickstart, I'm closing this issue.
