### ISSUE TITLE
How can I use my account to upload files my google drive account without browser interaction?

### ISSUE THREAD

**Issue by vishalkukkarequilar** [gsuitedevs/java-samples#20]
I want to upload some files to google drive every day and share the link with particular users but sample code mentioned on google drive API's page needs browsers interaction to upload files.

**Comment by asrivas** [comment]
Which sample code are you referring to?
You should be able to use one of these types of uploads:
https://developers.google.com/drive/api/v3/manage-uploads

Then share the file:
https://developers.google.com/drive/api/v3/manage-sharing

**Comment by grant** [comment]
A user has to only authenticate once.
After authenticating, you can upload files using examples in the links provided in the above comment.

Feel free to comment if you have additional issues. Closing.

**Comment by vishalkukkarequilar** [comment]
Yes, I got it.Following are the steps if anybody needs it in future

`Steps :

1) Enable the google drive API access:
https://console.developers.google.com/apis/library/drive.googleapis.com?id=e44a1596-da14-427c-9b36-5eb6acce3775&project=ancient-tractor-213403

2) Register a service account :
https://console.cloud.google.com/projectselector/iam-admin/serviceaccounts?supportedpurview=project&project=&folder=&organizationId=

Steps : Click on Create --> Project Name: upload example --> Create

3) Click on the top of the page CREATE SERVICE ACCOUNT

Steps: Service account name: upload-example --> Role: Owner -->Click
on Finish new private key --> Save

It should download json.(copy it to project src/java/resources for java project)

4) Click Service accounts tab on left. Copy the Email (Example:
upload-example@upload-example.iam.gserviceaccount.com
)

5)Create a folder in google drive where you want to upload files.
Right Click on folder  -> Click on
Advance -> Click on share -> under Add people tab add copied email (add can
organize, add and edit as permissions)`
