### ISSUE TITLE
What is this  return new AuthorizationCodeInstalledApp(flow, new LocalServerReceiver()).authorize("user");

### ISSUE THREAD

**Issue by khmereshop** [gsuitedevs/java-samples#21]
(Please fill out these details before submitting an issue)

### Sample Name
(i.e. Gmail Quickstart)

### Specifications
  - Java version (`java -version`)
  - OS (Mac/Linux/Windows)

I get error. It can't find the dependency for AuthorizationCodeInstalledApp and LocalServerReceiver()

I try to use it with maven spring boot application.

**Comment by asrivas** [comment]
This sample uses gradle, if you have any issues when using the gradle build system please file another issue but for maven, I'd ask on StackOverflow.
