### ISSUE TITLE
Didn't find class "java.awt.Desktop" site:stackoverflow.com

### ISSUE THREAD

**Issue by GuyDviri** [gsuitedevs/java-samples#27]
(Please fill out these details before submitting an issue)

### Sample Name
(i.e. PeopleAPI Quickstart)

### Expected Behavior
  return new AuthorizationCodeInstalledApp(flow, new LocalServerReceiver()).authorize(user);

### Specifications
  - Java version (`java -version`) 1-8
  - OS (Mac/Linux/Windows) win 10

**Comment by asrivas** [comment]
Can you paste your error logs?

**Comment by GuyDviri** [comment]
Thanks already solve it.

Collection<String> scopes = new ArrayList<>();
scopes.add(Scopes.PROFILE);
credential = GoogleAccountCredential.usingOAuth2( this, scopes);

credential.setSelectedAccountName(mFirebaseAuth.getCurrentUser().
getEmail());

userProfile = null;

PeopleService service = new PeopleService.Builder(http_transport, JSON_FACTORY, credential)
.setApplicationName(mainActivity.getResources().getString(R.string.app_name)).build();
Person userProfile = service.people().get("people/100889827937171513174").setRequestMaskIncludeField("person.biographies,person.birthdays,person.genders,person.phone_numbers").execute();


but .. it's strange I don't  find a way to get all user profile pictures.

**Comment by ganesh04071996** [comment]
i am also getting the same error. Please reopen this issue and please see my error log cat below

`java.lang.ClassNotFoundException: Didn't find class "java.awt.Desktop" on path: DexPathList[[zip file "/data/app/com.example.test.googledrive-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.test.googledrive-2/lib/arm, /system/lib, /vendor/lib]]`
