### ISSUE TITLE
Can not run the sample

### ISSUE THREAD

**Issue by MAsterWAynEe** [gsuitedevs/java-samples#28]
Project Folder\eclipse-workspace\Whatsapp_Business\bin\src\main\java>gradle -q run

FAILURE: Build failed with an exception.

* What went wrong:
Task 'run' not found in root project 'java'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by asrivas** [comment]
Which quickstart or sample are you trying to run?
You'll need navigate to the directory where the specific gradle files are to run that command.

For example, if I wanted to run the calendar quickstart, I'd need to navigate to:
/java-samples/calendar/quickstart

/java-samples/calendar/quickstart$ gradle -q run

**Comment by asrivas** [comment]
friendly ping, let us know if you're still having this issue -- thanks!

**Comment by Luc4s99** [comment]
I had the same problem. But I tried running the "gradle -q run" command where gradle files are as you said, and it worked.

**Comment by grant** [comment]
Maybe we should add a README per quickstart directory.

**Comment by asrivas** [comment]
Great to hear it worked
