### ISSUE TITLE
SheetsQuickstart  java.lang.NullPointerException

### ISSUE THREAD

**Issue by svorugan** [gsuitedevs/java-samples#31]
(Please fill out these details before submitting an issue)

### SheetsQuickstart 
(i.e. Gmail Quickstart)

### NullPointerException
Exception in thread "main" java.lang.NullPointerException
	at java.io.Reader.<init>(Unknown Source)
	at java.io.InputStreamReader.<init>(Unknown Source)
	at ruhr.oracle.gclient.Auth.getCredentials(Auth.java:44)
	at ruhr.oracle.gclient.Auth.main(Auth.java:68)

### Specifications
  - Java version (`java -version`) : 1.8.0_181
  - OS (Mac/Linux/Windows) : Windows

**Comment by erickoledadevrel** [comment]
Did you follow Step 2.b, and copy the `credentials.json`file you downloaded into `src/main/java src/main/resources`?

**Comment by Darkwiiyou** [comment]
I'm having this exact same issue, following the steps fully.

**Comment by erickoledadevrel** [comment]
Are you using the `gradle run` command to run the same, or running it from your IDE?

**Comment by Darkwiiyou** [comment]
I am running it from the IDE.

**Comment by erickoledadevrel** [comment]
Please try running it using the gradle command. The `credentials.json` file needs to be added to the Java project as a resource, so alternatively ensure that it is in your IDE.
