### ISSUE TITLE
issue running AppScript using my local code.

### ISSUE THREAD

**Issue by ghost** [gsuitedevs/java-samples#36]
Hi please suggest me on the issue I am trying to run the given code below, where "myApp" is function Name in the Script which I am trying to run.

```
 ExecutionRequest request = new ExecutionRequest().setFunction("myApp").setDevMode(true);
       try {
            Operation op = service.scripts().run("1sdEPN6es8E3sXTiPJWlhAZkPwRjsnLzW_dPyP6EC3BWjmu65jhkUfbUa", request).execute();
            // Print results of request.
            if (op.getError() != null) {
                // The API executed, but the script returned an error.
                System.out.println("Error");
            } else {
                System.out.println("Success");
            }
        } catch (GoogleJsonResponseException e) {
            e.printStackTrace(System.out);
        }

```
Its giveing error like:

>  {
>   "code" : 404,
>   "errors" : [ {
>     "domain" : "global",
>     "message" : "Requested entity was not found.",
>     "reason" : "notFound"
>   } ],
>   "message" : "Requested entity was not found.",
>   "status" : "NOT_FOUND"
> }
> 

or if I am deploying this as the web app it's giving this type of error:

> com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
> {
>   "code" : 403,
>   "errors" : [ {
>     "domain" : "global",
>     "message" : "The caller does not have permission",
>     "reason" : "forbidden"
>   } ],
>   "message" : "The caller does not have permission",
>   "status" : "PERMISSION_DENIED"
> }

What i have to do run the code perfectly???? 
### Specifications
  - Java version (`1.8`)
  - OS (Linux)

**Comment by erickoledadevrel** [comment]
The `NOT_FOUND` indicates that the script was not published as an API executable. The `PERMISSION_DENIED` error indicates that the OAuth client of the calling application is not in the same Cloud Console project as the target Apps Script. This guide has more information:

https://developers.google.com/apps-script/api/how-tos/execute
