### ISSUE TITLE
Issue running SheetsQuickstart

### ISSUE THREAD

**Issue by NikRoberts1** [gsuitedevs/java-samples#37]
(Please fill out these details before submitting an issue)

### Sample Name
Sheets Quickstart

### Expected Behavior

As per https://developers.google.com/sheets/api/quickstart/java

### Actual Behavior

Please see attached screenshot
![sheets quickstart error](https://user-images.githubusercontent.com/43862278/46497990-0dba1480-c814-11e8-98cf-14ca32c54802.png)

### Specifications
  - Java version 

1.8.0_161
  - OS Widows 7

**Comment by erickoledadevrel** [comment]
Can you try making a cURL request to the same URL that is failing? I'm wondering if you have a proxy or other network configuration that is preventing gradle from downloading the library.

**Comment by NikRoberts1** [comment]
Hi,
Apologies for not replying sooner. Been away.
I am not too familiar with Curl so not 100% sure what you have asked me to check but I have had a go ... as shown in screengrab:
![2018-10-15 13_51_53-command prompt](https://user-images.githubusercontent.com/43862278/46952083-c1779b80-d081-11e8-95f0-1a537160111c.png)
I am not even sure I am attempting to download the correct file?
When I ran what I thought was correct ... it did not return anything!
Please advise next steps.
Nik

**Comment by erickoledadevrel** [comment]
Strange. Run the request again with the `-v` option so I can see the full output.

**Comment by erickoledadevrel** [comment]
Closing the issue due to inactivity.
