### ISSUE TITLE
credentials folder

### ISSUE THREAD

**Issue by moejamul** [gsuitedevs/java-samples#5]
Im getting an error, which path should i put instead of the credentials string?

**Comment by erickoledadevrel** [comment]
I'm not sure what you mean. Can you provide more detail about the error?

**Comment by grant** [comment]
If you're still experiencing this error, please refile the issue with specific details of which sample you're running and your operating system.

(I've created an `ISSUE_TEMPLATE` to enhance the quality of these GitHub issues.)
