### ISSUE TITLE
Clicking "Enable the Google Sheets API" Fails

### ISSUE THREAD

**Issue by jasonmm** [gsuitedevs/java-samples#50]
When clicking the "Enable the Google Sheets API" button on the Sheets Quickstart page I am presented with a dropdown to either select one of my existing projects or create a new project.  Regardless of whether I choose an existing project or create a new project, when "Next" is clicked an error is displayed.

### Sample Name
Google Sheets Quickstart

### Expected Behavior
I'm unsure, but I don't expect an error to be displayed.

### Actual Behavior
An error is displayed.  Usually "Something went wrong. Please try again.", but sometimes the message is blank.  Regardless of the error message a request is made right before the error to https://people-pa.clients6.google.com/v2/people that is returning

```
{
  "personResponse": [
    {
      "personId": "me",
      "status": "NOT_FOUND",
      "responseStatus": {
        "code": 5
      }
    }
  ]
}
```

### Specifications
  - Java version: `java version "1.8.0_172"`

**Comment by erickoledadevrel** [comment]
I'm not able to replicate this behavior, perhaps it was a temporary outage? If you are still getting this error please let us know.

**Comment by jasonmm** [comment]
Must have been a temporary outage.  I am now able to complete the quickstart without error.  Thank you.

**Comment by allquixotic** [comment]
This is happening for me now for the past hour. Exact same symptoms as the OP. Considering this last happened 12 days ago, it seems there is something intermittently wrong with this functionality.

**Comment by erickoledadevrel** [comment]
Thanks for the follow up. Are you still seeing this behavior today?
