### ISSUE TITLE
Button "Enable the Gmail API" not working

### ISSUE THREAD

**Issue by gundamsing** [gsuitedevs/java-samples#58]
(Please fill out these details before submitting an issue)

### Gmail Quickstart
https://developers.google.com/gmail/api/quickstart/java
### Expected Behavior
new dialog should be opened, json file should be downloaded
### Actual Behavior
the dialog windows loaded forever, no file is downloaded
### Specifications
  - Windows 10 and Mac, 
  - Chrome, Firefox, Safari
  - Windows firewall is shutdown

**Comment by erickoledadevrel** [comment]
Can you take a look in your Chrome console and see if there are any errors reported?

**Comment by gundamsing** [comment]
i have solved the problem by myself. i must using my gmail account to accept a agreement of "google cloud platform service and any suitable service and api" in https://console.developers.google.com. then the button works

**Comment by erickoledadevrel** [comment]
Thanks for the additional information. It looks like a recent change to the button code broke the flow for users that hadn't already accepted the TOS. We've reverted the change.
