### ISSUE TITLE
upload files to google drive in java

### ISSUE THREAD

**Issue by merlydavidson** [gsuitedevs/java-samples#62]
(Please fill out these details before submitting an issue)

### Sample Name
(i.e. Gmail Quickstart)

### Actual Behavior
Exception in thread "main" com.google.api.client.googleapis.json.GoogleJsonRespo
nseException: 403 Forbidden
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "Insufficient Permission: Request had insufficient authenticatio
n scopes.",
    "reason" : "insufficientPermissions"
  } ],
  "message" : "Insufficient Permission: Request had insufficient authentication
scopes."
### Specifications
  - Java version (`java -version`)
  - OS (Mac/Linux/Windows)

**Comment by erickoledadevrel** [comment]
Like in issue #34, the problem is likely that you changed the scopes but didn't delete the previous tokens.
