### ISSUE TITLE
Could not resolve all files for configuration ':compileClasspath'.

### ISSUE THREAD

**Issue by arindamdey1997** [gsuitedevs/java-samples#65]
Could not resolve all files for configuration ':compileClasspath'.
> Could not resolve com.google.api-client:google-api-client:1.23.0.
  Required by:
      project :
   > Could not resolve com.google.api-client:google-api-client:1.23.0.
      > Could not get resource 'https://repo.maven.apache.org/maven2/com/google/api-client/google-api-client/1.23.0/google-api-client-1.23.0.pom'.
         > Could not GET 'https://repo.maven.apache.org/maven2/com/google/api-client/google-api-client/1.23.0/google-api-client-1.23.0.pom'.
            > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.120.215] failed: Connection refused: connect
> Could not resolve com.google.oauth-client:google-oauth-client-jetty:1.23.0.
  Required by:
      project :
   > Could not resolve com.google.oauth-client:google-oauth-client-jetty:1.23.0.
      > Could not get resource 'https://repo.maven.apache.org/maven2/com/google/oauth-client/google-oauth-client-jetty/1.23.0/google-oauth-client-jetty-1.23.0.pom'.
         > Could not GET 'https://repo.maven.apache.org/maven2/com/google/oauth-client/google-oauth-client-jetty/1.23.0/google-oauth-client-jetty-1.23.0.pom'.
            > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.120.215] failed: Connection refused: connect
> Could not resolve com.google.apis:google-api-services-appsactivity:v1-rev136-1.23.0.
  Required by:
      project :
   > Could not resolve com.google.apis:google-api-services-appsactivity:v1-rev136-1.23.0.
      > Could not get resource 'https://repo.maven.apache.org/maven2/com/google/apis/google-api-services-appsactivity/v1-rev136-1.23.0/google-api-services-appsactivity-v1-rev136-1.23.0.pom'.
         > Could not GET 'https://repo.maven.apache.org/maven2/com/google/apis/google-api-services-appsactivity/v1-rev136-1.23.0/google-api-services-appsactivity-v1-rev136-1.23.0.pom'.
            > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.120.215] failed: Connection refused: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by erickoledadevrel** [comment]
It's likely that you have software on your computer that is blocking the connect to the maven server. See #13 where a user was able to find a solution.
