### ISSUE TITLE
Google Sheet API Import Error

### ISSUE THREAD

**Issue by amenkes319** [gsuitedevs/java-samples#66]
### Sample Name
Spreadsheet Quickstart

### Expected Behavior
Run Successfully

### Actual Behavior
Build Failed

### Specifications
  - 1.8.0_191
  - Windows

I use Eclipse Neon for JavaFX and when I copy and paste the test code from the Quickstart Guide it gives me error for all com.google imports saying they can not be resolved.

`Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	NetHttpTransport cannot be resolved to a type
	GoogleNetHttpTransport cannot be resolved
	Sheets cannot be resolved to a type
	Builder cannot be resolved to a type
	Sheets cannot be resolved to a type
	JsonFactory cannot be resolved to a type
	ValueRange cannot be resolved to a type`

**Comment by erickoledadevrel** [comment]
Please follow the steps in the quickstart to install the libraries:

https://developers.google.com/sheets/api/quickstart/java
