### ISSUE TITLE
How to read numbers as numeric values?

### ISSUE THREAD

**Issue by Syed-SnapLogic** [gsuitedevs/java-samples#7]
I have a spreadsheet with few columns as of type Number.  The values of those columns are aligned to the right in the spreadsheet.

![image](https://user-images.githubusercontent.com/5888194/42619055-96586382-85d4-11e8-9414-b02b8e847980.png)

When I read the sheet using the code snippet you provided, its rendering numeric values also as of type string.

![image](https://user-images.githubusercontent.com/5888194/42619107-b73d6d18-85d4-11e8-870d-b0ca04cad7ea.png)

In my project that I am working on right now, I need to read numbers as numeric types not as text.  Can you pls help me on this?

**Comment by erickoledadevrel** [comment]
This issue tracker is for reporting bugs in our sample code. For general Q&A, see the [Sheets API's support page0(https://developers.google.com/sheets/api/support) for options.

You can use [`spreadsheets.get`](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/get) to get a richer view of the data in a spreadsheet.
