### ISSUE TITLE
The requested URL /Callback was not found on this server

### ISSUE THREAD

**Issue by LambdaLambdaLambda** [gsuitedevs/java-samples#77]
### Sample Name
SheetsQuickstart

### Expected Behavior
Print on the console values taken in the range "Class Data!A2:E" from the spreadsheet "1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms"

### Actual Behavior

Browser opens up, asks for Google login and then in the browser appears the message "The requested URL /Callback was not found on this server".

### Specifications
  - Java version (`Java 1.8.0_191`)
  - OS (Mac)

**Comment by erickoledadevrel** [comment]
Are there any errors output in the console that was used to run `gradle run`?

**Comment by LambdaLambdaLambda** [comment]
Thank you for the reply. I just solved the problem changing the server port form 8888 to 9000.
