### ISSUE TITLE
Authorization Error 

### ISSUE THREAD

**Issue by tanayshah49** [gsuitedevs/java-samples#78]
(Please fill out these details before submitting an issue)

### Sheets Quickstart
(i.e. Gmail Quickstart)

### Authorization error : 403 and 401

I have the credentials.json file and also generated it from Oauth client ID in GCC, but however on GCC it says that the apps needs to be verified but it just a test app, so I don't have a landing url so how do I do that?

So not matter what I am not able to connect to the sheets, and just get authorization error.

### Specifications
  - 1.8 (`java -version`)
  - OS (Mac/Linux/Windows)

**Comment by asrivas** [comment]
You don't need to go through verification for this case: https://support.google.com/cloud/answer/7454865?hl=en
Click through where it says Advanced on the bottom of the dialog box to continue

**Comment by erickoledadevrel** [comment]
More information on verification is available in the troubleshooting section of the quickstart: https://developers.google.com/sheets/api/quickstart/java#troubleshooting
