### ISSUE TITLE
From where we need to get the tokens?

### ISSUE THREAD

**Issue by subashdbc** [gsuitedevs/java-samples#79]
### Drive Quickstart

I have the credentials.json file, but I am not sure from where these tokens are generated and used here,
`private static final String TOKENS_DIRECTORY_PATH = "tokens";`
Not sure how the above has to be generated

Could you please tell us how this is done?

### Specifications
  - Java version (`1.8`)
  - OS (Windows)

**Comment by erickoledadevrel** [comment]
The tokens are created automatically when `getCredentials` is run.

**Comment by subashdbc** [comment]
@erickoledadevrel thanks for the response
