### ISSUE TITLE
Will StoreCredential file work on Android?

### ISSUE THREAD

**Issue by subashdbc** [gsuitedevs/java-samples#81]
### Drive Quickstart
I just try to run the sample application with JAVA, it works as expected. But when I try to run from the Android application the `StoreCredential` file is getting created successfully but the browser doesn't get triggered up for reading the user information. 

```
GoogleAuthorizationCodeFlow flow = new GoogleAuthorizationCodeFlow.Builder(HTTP_TRANSPORT, JSON_FACTORY,
	   clientSecrets, SCOPES).setDataStoreFactory(new FileDataStoreFactory(CREDENTIALS_FOLDER))
	                        .setAccessType("offline").build();
return new AuthorizationCodeInstalledApp(flow, new LocalServerReceiver()).authorize("user");
```

Is it something which will not work for Android apps? Please do help us to know this.

### Specifications
  - Java version (`1.8`)
  - OS (Windows)

**Comment by erickoledadevrel** [comment]
This sample only works for command line applications. For an Android app, see the instructions here:

https://developers.google.com/api-client-library/java/google-api-java-client/android
