### ISSUE TITLE
Different port every run of the App

### ISSUE THREAD

**Issue by PavloZvarych** [gsuitedevs/java-samples#9]
Error: redirect_uri_mismatch
The redirect URI in the request, http://localhost:54673/Callback, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit...

Every time the App is in run, the port is different, hence it's hard to authorize a redirect URI

**Comment by erickoledadevrel** [comment]
Did you create the OAuth client via the button on the quickstart page? If so, it should be of type "Other", which doesn't allow you to specify redirect URIs.

**Comment by PavloZvarych** [comment]
Nope. But found a solution: how to set up port before the call
